# Generated by Django 2.1.7 on 2019-03-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.CharField(default='anonymous user', max_length=50, null=True),
        ),
    ]
