# Generated by Django 2.1.7 on 2019-03-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_feedback_user'),
    ]
    atomic = False
    
    operations = [
        migrations.RenameModel(
            old_name='listing',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='listing',
            new_name='product',
        ),
    ]
