# Generated by Django 2.1.7 on 2019-03-25 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20190325_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.ForeignKey(default='NA', null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.feedback'),
        ),
    ]
