# Generated by Django 2.1.7 on 2019-03-26 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20190325_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.ForeignKey(default='NA', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='reviews.feedback'),
        ),
    ]
